name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        std: [23]
        build_type: [Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD:STRING=${{matrix.std}} -DIRIS_BUILD_EXAMPLE=ON -DIRIS_BUILD_TESTING=ON

    - name: Build
      run: |
        $num_processors = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel $num_processors

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure
